#!/usr/bin/env python3
"""Validate AI Workflow V2 contracts and generate deterministic runtime adapters."""

from __future__ import annotations

import argparse
from datetime import date, datetime
import json
from pathlib import Path, PurePosixPath
import re
import subprocess
import sys
from typing import Any

try:
    from jsonschema import Draft202012Validator, FormatChecker
except ImportError as exc:  # pragma: no cover - environment diagnostic
    raise SystemExit("Missing dependency: install requirements-dev.txt") from exc


ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "contracts" / "schemas" / "v1"
GENERATED_HEADER = "GENERATED BY tools/workflowctl.py — DO NOT EDIT."
FORMAT_CHECKER = FormatChecker()
EFFECT_RANK = {name: index for index, name in enumerate(("E0", "E1", "E2", "E3", "E4", "E5", "E6", "E7"))}


@FORMAT_CHECKER.checks("date-time")
def valid_date_time(value: object) -> bool:
    if not isinstance(value, str):
        return True
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        return parsed.tzinfo is not None
    except ValueError:
        return False


@FORMAT_CHECKER.checks("date")
def valid_date(value: object) -> bool:
    if not isinstance(value, str):
        return True
    try:
        date.fromisoformat(value)
        return True
    except ValueError:
        return False


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        value = json.load(handle)
    if not isinstance(value, dict):
        raise ValueError(f"{path.relative_to(ROOT)}: root must be an object")
    return value


def root_path(relative: str) -> Path:
    path = (ROOT / relative).resolve()
    try:
        path.relative_to(ROOT)
    except ValueError as exc:
        raise ValueError(f"Path escapes repository: {relative}") from exc
    return path


def schema(name: str) -> dict[str, Any]:
    path = (SCHEMAS / name).resolve()
    if path.parent != SCHEMAS.resolve() or not path.is_file():
        raise ValueError(f"Unknown schema: {name}")
    return load_json(path)


def validation_errors(instance: dict[str, Any], schema_name: str) -> list[str]:
    validator = Draft202012Validator(schema(schema_name), format_checker=FORMAT_CHECKER)
    return [error.message for error in sorted(validator.iter_errors(instance), key=lambda item: list(item.path))]


def validate_schemas(errors: list[str]) -> None:
    for path in sorted(SCHEMAS.glob("*.schema.json")):
        try:
            Draft202012Validator.check_schema(load_json(path))
        except Exception as exc:  # jsonschema exposes several schema exceptions
            errors.append(f"{path.relative_to(ROOT)}: invalid schema: {exc}")


def validate_instance(path: Path, schema_name: str, errors: list[str]) -> None:
    try:
        instance = load_json(path)
        for message in validation_errors(instance, schema_name):
            errors.append(f"{path.relative_to(ROOT)}: {message}")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        errors.append(str(exc))


def validate_contract_suite(errors: list[str]) -> None:
    suite_path = ROOT / "evals" / "cases" / "v2-contract-suite.json"
    suite = load_json(suite_path)
    cases = suite.get("cases")
    if not isinstance(cases, list):
        errors.append(f"{suite_path.relative_to(ROOT)}: cases must be a list")
        return
    seen: set[str] = set()
    for case in cases:
        if not isinstance(case, dict):
            errors.append("v2 contract suite: case must be an object")
            continue
        case_id = case.get("id")
        if not isinstance(case_id, str) or not case_id:
            errors.append("v2 contract suite: case id must be non-empty")
            continue
        if case_id in seen:
            errors.append(f"v2 contract suite: duplicate id {case_id}")
        seen.add(case_id)
        try:
            fixture = load_json(root_path(case["fixture"]))
            actual_valid = not validation_errors(fixture, case["schema"])
            if actual_valid is not case.get("expected_valid"):
                detail = validation_errors(fixture, case["schema"])
                errors.append(f"{case_id}: expected_valid={case.get('expected_valid')}, actual={actual_valid}, errors={detail}")
        except (KeyError, OSError, ValueError, json.JSONDecodeError) as exc:
            errors.append(f"{case_id}: {exc}")


def normalize_scope(value: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError("Scope path must be a non-empty repository-relative string")
    raw = value.strip().replace("\\", "/")
    candidate = PurePosixPath(raw)
    if candidate.is_absolute() or re.match(r"^[A-Za-z]:", raw) or ".." in candidate.parts:
        raise ValueError(f"Unsafe repository scope: {value}")
    normalized = candidate.as_posix()
    if normalized in {"", "."}:
        raise ValueError(f"Unsafe repository scope: {value}")
    return normalized.rstrip("/")


def paths_overlap(first: str, second: str) -> bool:
    a, b = normalize_scope(first), normalize_scope(second)
    return a == b or a.startswith(f"{b}/") or b.startswith(f"{a}/")


def path_allowed(path: str, scopes: list[str]) -> bool:
    return any(paths_overlap(path, scope) and (normalize_scope(path) == normalize_scope(scope) or normalize_scope(path).startswith(f"{normalize_scope(scope)}/")) for scope in scopes)


def semantic_case(case: dict[str, Any]) -> set[str]:
    codes: set[str] = set()
    task = load_json(root_path(case["task"]))
    delegations = [load_json(root_path(item)) for item in case.get("delegations", [])]
    handoffs = [load_json(root_path(item)) for item in case.get("handoffs", [])]
    integration = load_json(root_path(case["integration"]))
    task_authority = task.get("authority", {})
    task_write_paths = task_authority.get("write_paths", [])
    protected_paths = task_authority.get("protected_paths", [])
    task_effect = task_authority.get("max_effect_class", "E0")

    for left_index, left in enumerate(delegations):
        if left.get("parent_task_id") != task.get("task_id"):
            codes.add("PARENT_TASK_MISMATCH")
        if EFFECT_RANK.get(left.get("max_effect_class", "E0"), 99) > EFFECT_RANK.get(task_effect, -1):
            codes.add("AUTHORITY_ESCALATION")
        try:
            if any(not path_allowed(path, task_write_paths) for path in left.get("write_set", [])):
                codes.add("DELEGATED_SCOPE_EXCEEDS_TASK")
            if any(paths_overlap(path, protected) for path in left.get("write_set", []) for protected in protected_paths):
                codes.add("PROTECTED_PATH_DELEGATED")
        except ValueError:
            codes.add("UNSAFE_PATH")
        if left.get("write_set") and "filesystem.write" not in left.get("tools_allowed", []):
            codes.add("WRITE_TOOL_MISSING")
        if left.get("workspace_isolation") == "worktree" and left.get("base_revision") != integration.get("baseline_revision"):
            codes.add("BASE_REVISION_MISMATCH")
        for right in delegations[left_index + 1 :]:
            if any(paths_overlap(a, b) for a in left.get("write_set", []) for b in right.get("write_set", [])):
                codes.add("WRITE_SET_CONFLICT")

    by_id = {item.get("delegation_id"): item for item in delegations}
    for handoff in handoffs:
        delegation = by_id.get(handoff.get("delegation_id"))
        if delegation is None or handoff.get("task_id") != task.get("task_id"):
            codes.add("HANDOFF_ID_MISMATCH")
            continue
        if handoff.get("from") != delegation.get("delegate"):
            codes.add("HANDOFF_ACTOR_MISMATCH")
        try:
            if any(not path_allowed(path, delegation.get("write_set", [])) for path in handoff.get("files_touched", [])):
                codes.add("WRITE_SCOPE_VIOLATION")
        except ValueError:
            codes.add("UNSAFE_PATH")
        if handoff.get("status") == "completed":
            expected_criteria = set(delegation.get("acceptance_criteria", []))
            results = handoff.get("acceptance_results", [])
            passed = {item.get("criterion_id") for item in results if item.get("result") == "passed"}
            if passed != expected_criteria:
                codes.add("ACCEPTANCE_INCOMPLETE")

    expected_owner = task.get("integrator")
    if integration.get("integrator") != expected_owner or integration.get("final_answer_owner") != expected_owner:
        codes.add("FINAL_OWNER_MISMATCH")
    if integration.get("parent_task_id") != task.get("task_id"):
        codes.add("PARENT_TASK_MISMATCH")
    if len(delegations) > task.get("budget", {}).get("max_children", 0):
        codes.add("CHILD_BUDGET_EXCEEDED")
    return codes


def validate_orchestration_suite(errors: list[str]) -> None:
    suite = load_json(ROOT / "evals" / "cases" / "v2-orchestration-suite.json")
    for case in suite.get("cases", []):
        try:
            fixture_specs = [(case["task"], "work-item.schema.json"), (case["integration"], "integration-plan.schema.json")]
            fixture_specs.extend((item, "delegation-packet.schema.json") for item in case.get("delegations", []))
            fixture_specs.extend((item, "handoff.schema.json") for item in case.get("handoffs", []))
            fixture_errors: list[str] = []
            for relative, schema_name in fixture_specs:
                messages = validation_errors(load_json(root_path(relative)), schema_name)
                fixture_errors.extend(f"{relative}: {message}" for message in messages)
            if fixture_errors:
                errors.append(f"orchestration {case.get('id')}: invalid fixtures {fixture_errors}")
                continue
            actual = semantic_case(case)
            expected = set(case.get("expected_errors", []))
            if actual != expected:
                errors.append(f"orchestration {case.get('id')}: expected {sorted(expected)}, got {sorted(actual)}")
        except (KeyError, OSError, ValueError, json.JSONDecodeError) as exc:
            errors.append(f"orchestration {case.get('id')}: {exc}")


def validate_state_machine(errors: list[str]) -> None:
    path = ROOT / "orchestration" / "state-machines" / "task-lifecycle.json"
    data = load_json(path)
    for message in validation_errors(data, "state-machine.schema.json"):
        errors.append(f"{path.relative_to(ROOT)}: {message}")
    states = set(data.get("states", []))
    if data.get("initial_state") not in states:
        errors.append("task lifecycle: initial_state is unknown")
    terminal = set(data.get("terminal_states", []))
    if not terminal <= states:
        errors.append("task lifecycle: terminal state is unknown")
    seen: set[tuple[str, str]] = set()
    for item in data.get("transitions", []):
        edge = (item.get("from"), item.get("to"))
        if not set(edge) <= states:
            errors.append(f"task lifecycle: transition uses unknown state {edge}")
        if edge in seen:
            errors.append(f"task lifecycle: duplicate transition {edge}")
        seen.add(edge)
        if edge[0] in terminal:
            errors.append(f"task lifecycle: terminal state has outgoing transition {edge}")
    restricted = {item.get("to"): set(item.get("allowed_roles", [])) for item in data.get("restricted_transitions", [])}
    for state in ("INTEGRATING", "VERIFIED", "COMPLETED"):
        if restricted.get(state) != {"integrator"}:
            errors.append(f"task lifecycle: {state} must be restricted to integrator")


def status_event_codes(event: dict[str, Any], machine: dict[str, Any]) -> set[str]:
    codes: set[str] = set()
    edges = {(item["from"], item["to"]) for item in machine["transitions"]}
    if event.get("from_state") is not None and (event.get("from_state"), event.get("to_state")) not in edges:
        codes.add("ILLEGAL_TRANSITION")
    restrictions = {item["to"]: set(item["allowed_roles"]) for item in machine["restricted_transitions"]}
    allowed = restrictions.get(event.get("to_state"))
    if allowed is not None and event.get("actor") not in allowed:
        codes.add("ROLE_NOT_ALLOWED")
    return codes


def validate_status_suite(errors: list[str]) -> None:
    machine = load_json(ROOT / "orchestration" / "state-machines" / "task-lifecycle.json")
    suite = load_json(ROOT / "evals" / "cases" / "v2-state-suite.json")
    for case in suite.get("cases", []):
        try:
            event = load_json(root_path(case["fixture"]))
            schema_errors = validation_errors(event, "status-event.schema.json")
            if schema_errors:
                errors.append(f"state {case.get('id')}: invalid fixture: {schema_errors}")
                continue
            actual = status_event_codes(event, machine)
            expected = set(case.get("expected_errors", []))
            if actual != expected:
                errors.append(f"state {case.get('id')}: expected {sorted(expected)}, got {sorted(actual)}")
        except (KeyError, OSError, ValueError, json.JSONDecodeError) as exc:
            errors.append(f"state {case.get('id')}: {exc}")


def agent_instruction(card: dict[str, Any]) -> str:
    lines = [
        f"Purpose: {card['purpose']}",
        "Route only when: " + "; ".join(card["route_when"]),
        "Do not route when: " + "; ".join(card["do_not_route_when"]),
        "Required outputs: " + ", ".join(card["output_contracts"]),
        "Constraints: " + "; ".join(card["risk_limits"] + card["runtime_constraints"]),
        "Return a concise result with artifacts, evidence, risks, remaining work, and next action.",
    ]
    return "\n".join(lines)


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def claude_tools(card: dict[str, Any]) -> list[str]:
    allowed = card["tools_allowed"]
    tools = ["Read", "Grep", "Glob"]
    if "shell.read" in allowed or "shell.write" in allowed:
        tools.extend(["Bash", "PowerShell"])
    if "filesystem.write" in allowed:
        tools.extend(["Edit", "Write"])
    if "web.read" in allowed:
        tools.extend(["WebFetch", "WebSearch"])
    if "agent.delegate" in allowed:
        tools.append("Agent")
    return list(dict.fromkeys(tools))


def antigravity_tools(card: dict[str, Any]) -> list[str]:
    allowed = card["tools_allowed"]
    tools = ["view_file", "grep_search"]
    if "shell.read" in allowed or "shell.write" in allowed:
        tools.append("run_command")
    if "filesystem.write" in allowed:
        tools.append("replace_file_content")
    return tools


def expected_adapters() -> dict[Path, str]:
    result: dict[Path, str] = {}
    for path in sorted((ROOT / "agents" / "definitions").glob("*.json")):
        card = load_json(path)
        source = path.relative_to(ROOT).as_posix()
        body = agent_instruction(card)
        read_only = card["write_scope"] == "none"

        codex = (
            f"# {GENERATED_HEADER}\n# Source: {source}\n"
            f"name = {toml_string(card['agent_id'])}\n"
            f"description = {toml_string(card['purpose'])}\n"
            f"developer_instructions = {toml_string(body)}\n"
            f"sandbox_mode = {toml_string('read-only' if read_only else 'workspace-write')}\n"
        )
        result[ROOT / ".codex" / "agents" / f"{card['agent_id']}.toml"] = codex

        ctools = ", ".join(claude_tools(card))
        claude = (
            f"<!-- {GENERATED_HEADER} Source: {source} -->\n---\n"
            f"name: {card['agent_id']}\n"
            f"description: {yaml_string(card['purpose'])}\n"
            f"tools: {ctools}\n"
            f"permissionMode: {'plan' if read_only else 'default'}\n---\n\n"
            f"# System prompt\n\n{body}\n"
        )
        result[ROOT / ".claude" / "agents" / f"{card['agent_id']}.md"] = claude

        atools = "\n".join(f"  - {item}" for item in antigravity_tools(card))
        antigravity = (
            f"<!-- {GENERATED_HEADER} Source: {source} -->\n---\n"
            f"name: {card['agent_id']}\n"
            f"description: {yaml_string(card['purpose'])}\n"
            f"tools:\n{atools}\n"
            "mainAgent: false\nsubagent: true\nmodel: inherit\ncommandExecutionPolicy: sandbox\n---\n\n"
            f"# System prompt\n\n{body}\n"
        )
        result[ROOT / ".agents" / "agents" / f"{card['agent_id']}.md"] = antigravity
    return result


def adapter_drift() -> list[str]:
    expected = expected_adapters()
    drift: list[str] = []
    for path, content in expected.items():
        if not path.is_file():
            drift.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != content:
            drift.append(f"different {path.relative_to(ROOT)}")
    expected_paths = set(expected)
    for folder in (ROOT / ".codex" / "agents", ROOT / ".claude" / "agents", ROOT / ".agents" / "agents"):
        if folder.is_dir():
            for path in folder.iterdir():
                if path.is_file() and path not in expected_paths:
                    drift.append(f"unexpected {path.relative_to(ROOT)}")
    return drift


def generate_adapters() -> int:
    for path, content in expected_adapters().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            print(f"SKIP      {path.relative_to(ROOT)}")
            continue
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"GENERATED {path.relative_to(ROOT)}")
    return 0


def validate_context_budget(errors: list[str]) -> None:
    limits = {ROOT / "AGENTS.md": (120, 1000), ROOT / "WORKFLOW.md": (120, 1000)}
    for path, (line_limit, word_limit) in limits.items():
        text = path.read_text(encoding="utf-8")
        lines, words = len(text.splitlines()), len(text.split())
        if lines > line_limit or words > word_limit:
            errors.append(f"{path.name}: context budget exceeded ({lines} lines, {words} words)")
    for path in (ROOT / ".agents" / "skills").glob("*/SKILL.md"):
        if len(path.read_text(encoding="utf-8").splitlines()) > 500:
            errors.append(f"{path.relative_to(ROOT)}: exceeds 500 lines")


def validate_routes(errors: list[str]) -> None:
    path = ROOT / "registry" / "routes.json"
    try:
        data = load_json(path)
        for message in validation_errors(data, "route-registry.schema.json"):
            errors.append(f"{path.relative_to(ROOT)}: {message}")
        routes = data.get("routes", [])
        ids = [item.get("id") for item in routes if isinstance(item, dict)]
        if len(ids) != len(set(ids)):
            errors.append("registry/routes.json: duplicate route id")
        required = {"single-backend-api", "delegated-frontend", "parallel-fullstack", "api-sdk-application"}
        if not required <= set(ids):
            errors.append(f"registry/routes.json: missing required routes {sorted(required - set(ids))}")
        for route in routes:
            if not isinstance(route, dict):
                continue
            for relative in (*route.get("must_load", []), *route.get("retrieve_on_demand", []), *route.get("machine_contracts", [])):
                if not root_path(relative).is_file():
                    errors.append(f"route {route.get('id')}: missing {relative}")
            fixture = route.get("fixture")
            if fixture:
                fixture_path = root_path(fixture)
                if not fixture_path.is_file():
                    errors.append(f"route {route.get('id')}: missing fixture {fixture}")
                elif route.get("id") == "api-sdk-application":
                    for message in validation_errors(load_json(fixture_path), "work-item.schema.json"):
                        errors.append(f"route {route.get('id')}: fixture {message}")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        errors.append(str(exc))


def validate_all() -> list[str]:
    errors: list[str] = []
    validate_schemas(errors)
    validate_instance(ROOT / "aiwf.json", "project.schema.json", errors)
    for path in sorted((ROOT / "agents" / "definitions").glob("*.json")):
        validate_instance(path, "capability-card.schema.json", errors)
        try:
            card = load_json(path)
            can_write = "filesystem.write" in card.get("tools_allowed", [])
            if card.get("write_scope") == "none" and can_write:
                errors.append(f"{path.relative_to(ROOT)}: read-only role allows filesystem.write")
            if card.get("write_scope") != "none" and not can_write:
                errors.append(f"{path.relative_to(ROOT)}: writable role lacks filesystem.write")
        except (OSError, ValueError, json.JSONDecodeError) as exc:
            errors.append(str(exc))
    for path in sorted((ROOT / "agents" / "teams").glob("*.json")):
        validate_instance(path, "team-topology.schema.json", errors)
    for path in sorted((ROOT / "adapters").glob("*/manifest.json")):
        validate_instance(path, "adapter-manifest.schema.json", errors)
    validate_contract_suite(errors)
    validate_orchestration_suite(errors)
    validate_state_machine(errors)
    validate_status_suite(errors)
    validate_routes(errors)
    validate_context_budget(errors)
    for item in adapter_drift():
        errors.append(f"adapter drift: {item}")
    return errors


def git_head_available() -> bool:
    result = subprocess.run(["git", "rev-parse", "--verify", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=False)
    return result.returncode == 0


def status() -> int:
    project = load_json(ROOT / "aiwf.json")
    print(f"Project: {project['name']} ({project['schema_version']})")
    print(f"Git baseline: {'ready' if git_head_available() else 'missing'}")
    print(f"Worktree mode: {'ready' if project['worktree_ready'] and git_head_available() else 'not ready'}")
    print(f"Canonical agents: {len(list((ROOT / 'agents' / 'definitions').glob('*.json')))}")
    print(f"Adapter drift: {len(adapter_drift())}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("validate", help="Run V2 schema, semantic, adapter and context checks")
    sub.add_parser("generate-adapters", help="Regenerate runtime projections from canonical agent definitions")
    sub.add_parser("check-adapters", help="Check generated runtime projections for drift")
    sub.add_parser("context-budget", help="Check deterministic context size limits")
    sub.add_parser("status", help="Show baseline and adapter readiness")
    validate_file = sub.add_parser("validate-file", help="Validate one repository JSON file against a V1 schema")
    validate_file.add_argument("file", help="Repository-relative JSON file")
    validate_file.add_argument("--schema", required=True, choices=sorted(path.name for path in SCHEMAS.glob("*.schema.json")))
    args = parser.parse_args()

    if args.command == "generate-adapters":
        return generate_adapters()
    if args.command == "check-adapters":
        drift = adapter_drift()
        if drift:
            print("Adapter drift detected:")
            for item in drift:
                print(f"- {item}")
            return 1
        print("Adapter drift check passed.")
        return 0
    if args.command == "context-budget":
        errors: list[str] = []
        validate_context_budget(errors)
    elif args.command == "validate-file":
        try:
            instance = load_json(root_path(args.file))
            errors = [f"{args.file}: {item}" for item in validation_errors(instance, args.schema)]
        except (OSError, ValueError, json.JSONDecodeError) as exc:
            errors = [str(exc)]
    elif args.command == "status":
        return status()
    else:
        errors = validate_all()
    if errors:
        print("V2 validation failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    print("V2 validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
